repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        # language_version: python3
        # files: ^(*.py)
        # # exclude: ^(venv|config(.*).py)
        args: [-v]
        additional_dependencies:
          - "flake8-blind-except>=0.1.0,<1.0.0"
          - "flake8-builtins>=1.4.0,<2.0.0"
          - "flake8-import-order>=0.18.0,<1.0.0"
          - "pep8-naming>=0.8.0,<1.0.0"

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.1
    hooks:
      - id: python-safety-dependencies-check
        language_version: python3
        files: requirements(\-dev)?\.text$
